name: Update README.md

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: node ./src/index.js
    - run: |
        git config user.name fmarinoa
        git config user.email ${{ secrets.MAIL }}
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin main
